// Code generated by ent, DO NOT EDIT.

package apikeyriskevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldAPIKeyID, v))
}

// RuleCode applies equality check predicate on the "rule_code" field. It's identical to RuleCodeEQ.
func RuleCode(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldRuleCode, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldSeverity, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v int) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldScore, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldStatus, v))
}

// TimeBucket applies equality check predicate on the "time_bucket" field. It's identical to TimeBucketEQ.
func TimeBucket(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldTimeBucket, v))
}

// BlockedAt applies equality check predicate on the "blocked_at" field. It's identical to BlockedAtEQ.
func BlockedAt(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldBlockedAt, v))
}

// ResolvedAt applies equality check predicate on the "resolved_at" field. It's identical to ResolvedAtEQ.
func ResolvedAt(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedBy applies equality check predicate on the "resolved_by" field. It's identical to ResolvedByEQ.
func ResolvedBy(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldResolvedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldUserID, vs...))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// RuleCodeEQ applies the EQ predicate on the "rule_code" field.
func RuleCodeEQ(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldRuleCode, v))
}

// RuleCodeNEQ applies the NEQ predicate on the "rule_code" field.
func RuleCodeNEQ(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldRuleCode, v))
}

// RuleCodeIn applies the In predicate on the "rule_code" field.
func RuleCodeIn(vs ...string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldRuleCode, vs...))
}

// RuleCodeNotIn applies the NotIn predicate on the "rule_code" field.
func RuleCodeNotIn(vs ...string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldRuleCode, vs...))
}

// RuleCodeGT applies the GT predicate on the "rule_code" field.
func RuleCodeGT(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGT(FieldRuleCode, v))
}

// RuleCodeGTE applies the GTE predicate on the "rule_code" field.
func RuleCodeGTE(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGTE(FieldRuleCode, v))
}

// RuleCodeLT applies the LT predicate on the "rule_code" field.
func RuleCodeLT(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLT(FieldRuleCode, v))
}

// RuleCodeLTE applies the LTE predicate on the "rule_code" field.
func RuleCodeLTE(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLTE(FieldRuleCode, v))
}

// RuleCodeContains applies the Contains predicate on the "rule_code" field.
func RuleCodeContains(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldContains(FieldRuleCode, v))
}

// RuleCodeHasPrefix applies the HasPrefix predicate on the "rule_code" field.
func RuleCodeHasPrefix(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldHasPrefix(FieldRuleCode, v))
}

// RuleCodeHasSuffix applies the HasSuffix predicate on the "rule_code" field.
func RuleCodeHasSuffix(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldHasSuffix(FieldRuleCode, v))
}

// RuleCodeEqualFold applies the EqualFold predicate on the "rule_code" field.
func RuleCodeEqualFold(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEqualFold(FieldRuleCode, v))
}

// RuleCodeContainsFold applies the ContainsFold predicate on the "rule_code" field.
func RuleCodeContainsFold(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldContainsFold(FieldRuleCode, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldContainsFold(FieldSeverity, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v int) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v int) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...int) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...int) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v int) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v int) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v int) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v int) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLTE(FieldScore, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldContainsFold(FieldStatus, v))
}

// EvidenceIsNil applies the IsNil predicate on the "evidence" field.
func EvidenceIsNil() predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIsNull(FieldEvidence))
}

// EvidenceNotNil applies the NotNil predicate on the "evidence" field.
func EvidenceNotNil() predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotNull(FieldEvidence))
}

// TimeBucketEQ applies the EQ predicate on the "time_bucket" field.
func TimeBucketEQ(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldTimeBucket, v))
}

// TimeBucketNEQ applies the NEQ predicate on the "time_bucket" field.
func TimeBucketNEQ(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldTimeBucket, v))
}

// TimeBucketIn applies the In predicate on the "time_bucket" field.
func TimeBucketIn(vs ...time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldTimeBucket, vs...))
}

// TimeBucketNotIn applies the NotIn predicate on the "time_bucket" field.
func TimeBucketNotIn(vs ...time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldTimeBucket, vs...))
}

// TimeBucketGT applies the GT predicate on the "time_bucket" field.
func TimeBucketGT(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGT(FieldTimeBucket, v))
}

// TimeBucketGTE applies the GTE predicate on the "time_bucket" field.
func TimeBucketGTE(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGTE(FieldTimeBucket, v))
}

// TimeBucketLT applies the LT predicate on the "time_bucket" field.
func TimeBucketLT(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLT(FieldTimeBucket, v))
}

// TimeBucketLTE applies the LTE predicate on the "time_bucket" field.
func TimeBucketLTE(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLTE(FieldTimeBucket, v))
}

// BlockedAtEQ applies the EQ predicate on the "blocked_at" field.
func BlockedAtEQ(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldBlockedAt, v))
}

// BlockedAtNEQ applies the NEQ predicate on the "blocked_at" field.
func BlockedAtNEQ(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldBlockedAt, v))
}

// BlockedAtIn applies the In predicate on the "blocked_at" field.
func BlockedAtIn(vs ...time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldBlockedAt, vs...))
}

// BlockedAtNotIn applies the NotIn predicate on the "blocked_at" field.
func BlockedAtNotIn(vs ...time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldBlockedAt, vs...))
}

// BlockedAtGT applies the GT predicate on the "blocked_at" field.
func BlockedAtGT(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGT(FieldBlockedAt, v))
}

// BlockedAtGTE applies the GTE predicate on the "blocked_at" field.
func BlockedAtGTE(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGTE(FieldBlockedAt, v))
}

// BlockedAtLT applies the LT predicate on the "blocked_at" field.
func BlockedAtLT(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLT(FieldBlockedAt, v))
}

// BlockedAtLTE applies the LTE predicate on the "blocked_at" field.
func BlockedAtLTE(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLTE(FieldBlockedAt, v))
}

// BlockedAtIsNil applies the IsNil predicate on the "blocked_at" field.
func BlockedAtIsNil() predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIsNull(FieldBlockedAt))
}

// BlockedAtNotNil applies the NotNil predicate on the "blocked_at" field.
func BlockedAtNotNil() predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotNull(FieldBlockedAt))
}

// ResolvedAtEQ applies the EQ predicate on the "resolved_at" field.
func ResolvedAtEQ(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedAtNEQ applies the NEQ predicate on the "resolved_at" field.
func ResolvedAtNEQ(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldResolvedAt, v))
}

// ResolvedAtIn applies the In predicate on the "resolved_at" field.
func ResolvedAtIn(vs ...time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldResolvedAt, vs...))
}

// ResolvedAtNotIn applies the NotIn predicate on the "resolved_at" field.
func ResolvedAtNotIn(vs ...time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldResolvedAt, vs...))
}

// ResolvedAtGT applies the GT predicate on the "resolved_at" field.
func ResolvedAtGT(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGT(FieldResolvedAt, v))
}

// ResolvedAtGTE applies the GTE predicate on the "resolved_at" field.
func ResolvedAtGTE(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGTE(FieldResolvedAt, v))
}

// ResolvedAtLT applies the LT predicate on the "resolved_at" field.
func ResolvedAtLT(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLT(FieldResolvedAt, v))
}

// ResolvedAtLTE applies the LTE predicate on the "resolved_at" field.
func ResolvedAtLTE(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLTE(FieldResolvedAt, v))
}

// ResolvedAtIsNil applies the IsNil predicate on the "resolved_at" field.
func ResolvedAtIsNil() predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIsNull(FieldResolvedAt))
}

// ResolvedAtNotNil applies the NotNil predicate on the "resolved_at" field.
func ResolvedAtNotNil() predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotNull(FieldResolvedAt))
}

// ResolvedByEQ applies the EQ predicate on the "resolved_by" field.
func ResolvedByEQ(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldResolvedBy, v))
}

// ResolvedByNEQ applies the NEQ predicate on the "resolved_by" field.
func ResolvedByNEQ(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldResolvedBy, v))
}

// ResolvedByIn applies the In predicate on the "resolved_by" field.
func ResolvedByIn(vs ...int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldResolvedBy, vs...))
}

// ResolvedByNotIn applies the NotIn predicate on the "resolved_by" field.
func ResolvedByNotIn(vs ...int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldResolvedBy, vs...))
}

// ResolvedByGT applies the GT predicate on the "resolved_by" field.
func ResolvedByGT(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGT(FieldResolvedBy, v))
}

// ResolvedByGTE applies the GTE predicate on the "resolved_by" field.
func ResolvedByGTE(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGTE(FieldResolvedBy, v))
}

// ResolvedByLT applies the LT predicate on the "resolved_by" field.
func ResolvedByLT(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLT(FieldResolvedBy, v))
}

// ResolvedByLTE applies the LTE predicate on the "resolved_by" field.
func ResolvedByLTE(v int64) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLTE(FieldResolvedBy, v))
}

// ResolvedByIsNil applies the IsNil predicate on the "resolved_by" field.
func ResolvedByIsNil() predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIsNull(FieldResolvedBy))
}

// ResolvedByNotNil applies the NotNil predicate on the "resolved_by" field.
func ResolvedByNotNil() predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotNull(FieldResolvedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIKeyRiskEvent) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIKeyRiskEvent) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIKeyRiskEvent) predicate.APIKeyRiskEvent {
	return predicate.APIKeyRiskEvent(sql.NotPredicates(p))
}
