// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeyriskevent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// APIKeyRiskEventUpdate is the builder for updating APIKeyRiskEvent entities.
type APIKeyRiskEventUpdate struct {
	config
	hooks    []Hook
	mutation *APIKeyRiskEventMutation
}

// Where appends a list predicates to the APIKeyRiskEventUpdate builder.
func (_u *APIKeyRiskEventUpdate) Where(ps ...predicate.APIKeyRiskEvent) *APIKeyRiskEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *APIKeyRiskEventUpdate) SetUserID(v int64) *APIKeyRiskEventUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdate) SetNillableUserID(v *int64) *APIKeyRiskEventUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeyRiskEventUpdate) SetAPIKeyID(v int64) *APIKeyRiskEventUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdate) SetNillableAPIKeyID(v *int64) *APIKeyRiskEventUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetRuleCode sets the "rule_code" field.
func (_u *APIKeyRiskEventUpdate) SetRuleCode(v string) *APIKeyRiskEventUpdate {
	_u.mutation.SetRuleCode(v)
	return _u
}

// SetNillableRuleCode sets the "rule_code" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdate) SetNillableRuleCode(v *string) *APIKeyRiskEventUpdate {
	if v != nil {
		_u.SetRuleCode(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *APIKeyRiskEventUpdate) SetSeverity(v string) *APIKeyRiskEventUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdate) SetNillableSeverity(v *string) *APIKeyRiskEventUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *APIKeyRiskEventUpdate) SetScore(v int) *APIKeyRiskEventUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdate) SetNillableScore(v *int) *APIKeyRiskEventUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *APIKeyRiskEventUpdate) AddScore(v int) *APIKeyRiskEventUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *APIKeyRiskEventUpdate) SetStatus(v string) *APIKeyRiskEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdate) SetNillableStatus(v *string) *APIKeyRiskEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEvidence sets the "evidence" field.
func (_u *APIKeyRiskEventUpdate) SetEvidence(v map[string]interface{}) *APIKeyRiskEventUpdate {
	_u.mutation.SetEvidence(v)
	return _u
}

// ClearEvidence clears the value of the "evidence" field.
func (_u *APIKeyRiskEventUpdate) ClearEvidence() *APIKeyRiskEventUpdate {
	_u.mutation.ClearEvidence()
	return _u
}

// SetTimeBucket sets the "time_bucket" field.
func (_u *APIKeyRiskEventUpdate) SetTimeBucket(v time.Time) *APIKeyRiskEventUpdate {
	_u.mutation.SetTimeBucket(v)
	return _u
}

// SetNillableTimeBucket sets the "time_bucket" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdate) SetNillableTimeBucket(v *time.Time) *APIKeyRiskEventUpdate {
	if v != nil {
		_u.SetTimeBucket(*v)
	}
	return _u
}

// SetBlockedAt sets the "blocked_at" field.
func (_u *APIKeyRiskEventUpdate) SetBlockedAt(v time.Time) *APIKeyRiskEventUpdate {
	_u.mutation.SetBlockedAt(v)
	return _u
}

// SetNillableBlockedAt sets the "blocked_at" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdate) SetNillableBlockedAt(v *time.Time) *APIKeyRiskEventUpdate {
	if v != nil {
		_u.SetBlockedAt(*v)
	}
	return _u
}

// ClearBlockedAt clears the value of the "blocked_at" field.
func (_u *APIKeyRiskEventUpdate) ClearBlockedAt() *APIKeyRiskEventUpdate {
	_u.mutation.ClearBlockedAt()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *APIKeyRiskEventUpdate) SetResolvedAt(v time.Time) *APIKeyRiskEventUpdate {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdate) SetNillableResolvedAt(v *time.Time) *APIKeyRiskEventUpdate {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *APIKeyRiskEventUpdate) ClearResolvedAt() *APIKeyRiskEventUpdate {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetResolvedBy sets the "resolved_by" field.
func (_u *APIKeyRiskEventUpdate) SetResolvedBy(v int64) *APIKeyRiskEventUpdate {
	_u.mutation.ResetResolvedBy()
	_u.mutation.SetResolvedBy(v)
	return _u
}

// SetNillableResolvedBy sets the "resolved_by" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdate) SetNillableResolvedBy(v *int64) *APIKeyRiskEventUpdate {
	if v != nil {
		_u.SetResolvedBy(*v)
	}
	return _u
}

// AddResolvedBy adds value to the "resolved_by" field.
func (_u *APIKeyRiskEventUpdate) AddResolvedBy(v int64) *APIKeyRiskEventUpdate {
	_u.mutation.AddResolvedBy(v)
	return _u
}

// ClearResolvedBy clears the value of the "resolved_by" field.
func (_u *APIKeyRiskEventUpdate) ClearResolvedBy() *APIKeyRiskEventUpdate {
	_u.mutation.ClearResolvedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyRiskEventUpdate) SetUpdatedAt(v time.Time) *APIKeyRiskEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *APIKeyRiskEventUpdate) SetUser(v *User) *APIKeyRiskEventUpdate {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *APIKeyRiskEventUpdate) SetAPIKey(v *APIKey) *APIKeyRiskEventUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the APIKeyRiskEventMutation object of the builder.
func (_u *APIKeyRiskEventUpdate) Mutation() *APIKeyRiskEventMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *APIKeyRiskEventUpdate) ClearUser() *APIKeyRiskEventUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *APIKeyRiskEventUpdate) ClearAPIKey() *APIKeyRiskEventUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeyRiskEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyRiskEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeyRiskEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyRiskEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyRiskEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeyriskevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyRiskEventUpdate) check() error {
	if v, ok := _u.mutation.RuleCode(); ok {
		if err := apikeyriskevent.RuleCodeValidator(v); err != nil {
			return &ValidationError{Name: "rule_code", err: fmt.Errorf(`ent: validator failed for field "APIKeyRiskEvent.rule_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := apikeyriskevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "APIKeyRiskEvent.severity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := apikeyriskevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "APIKeyRiskEvent.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyRiskEvent.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyRiskEvent.api_key"`)
	}
	return nil
}

func (_u *APIKeyRiskEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeyriskevent.Table, apikeyriskevent.Columns, sqlgraph.NewFieldSpec(apikeyriskevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RuleCode(); ok {
		_spec.SetField(apikeyriskevent.FieldRuleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(apikeyriskevent.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(apikeyriskevent.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(apikeyriskevent.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(apikeyriskevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Evidence(); ok {
		_spec.SetField(apikeyriskevent.FieldEvidence, field.TypeJSON, value)
	}
	if _u.mutation.EvidenceCleared() {
		_spec.ClearField(apikeyriskevent.FieldEvidence, field.TypeJSON)
	}
	if value, ok := _u.mutation.TimeBucket(); ok {
		_spec.SetField(apikeyriskevent.FieldTimeBucket, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BlockedAt(); ok {
		_spec.SetField(apikeyriskevent.FieldBlockedAt, field.TypeTime, value)
	}
	if _u.mutation.BlockedAtCleared() {
		_spec.ClearField(apikeyriskevent.FieldBlockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(apikeyriskevent.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(apikeyriskevent.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResolvedBy(); ok {
		_spec.SetField(apikeyriskevent.FieldResolvedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResolvedBy(); ok {
		_spec.AddField(apikeyriskevent.FieldResolvedBy, field.TypeInt64, value)
	}
	if _u.mutation.ResolvedByCleared() {
		_spec.ClearField(apikeyriskevent.FieldResolvedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyriskevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyriskevent.UserTable,
			Columns: []string{apikeyriskevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyriskevent.UserTable,
			Columns: []string{apikeyriskevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyriskevent.APIKeyTable,
			Columns: []string{apikeyriskevent.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyriskevent.APIKeyTable,
			Columns: []string{apikeyriskevent.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeyriskevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeyRiskEventUpdateOne is the builder for updating a single APIKeyRiskEvent entity.
type APIKeyRiskEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIKeyRiskEventMutation
}

// SetUserID sets the "user_id" field.
func (_u *APIKeyRiskEventUpdateOne) SetUserID(v int64) *APIKeyRiskEventUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdateOne) SetNillableUserID(v *int64) *APIKeyRiskEventUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeyRiskEventUpdateOne) SetAPIKeyID(v int64) *APIKeyRiskEventUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdateOne) SetNillableAPIKeyID(v *int64) *APIKeyRiskEventUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetRuleCode sets the "rule_code" field.
func (_u *APIKeyRiskEventUpdateOne) SetRuleCode(v string) *APIKeyRiskEventUpdateOne {
	_u.mutation.SetRuleCode(v)
	return _u
}

// SetNillableRuleCode sets the "rule_code" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdateOne) SetNillableRuleCode(v *string) *APIKeyRiskEventUpdateOne {
	if v != nil {
		_u.SetRuleCode(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *APIKeyRiskEventUpdateOne) SetSeverity(v string) *APIKeyRiskEventUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdateOne) SetNillableSeverity(v *string) *APIKeyRiskEventUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *APIKeyRiskEventUpdateOne) SetScore(v int) *APIKeyRiskEventUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdateOne) SetNillableScore(v *int) *APIKeyRiskEventUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *APIKeyRiskEventUpdateOne) AddScore(v int) *APIKeyRiskEventUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *APIKeyRiskEventUpdateOne) SetStatus(v string) *APIKeyRiskEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdateOne) SetNillableStatus(v *string) *APIKeyRiskEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEvidence sets the "evidence" field.
func (_u *APIKeyRiskEventUpdateOne) SetEvidence(v map[string]interface{}) *APIKeyRiskEventUpdateOne {
	_u.mutation.SetEvidence(v)
	return _u
}

// ClearEvidence clears the value of the "evidence" field.
func (_u *APIKeyRiskEventUpdateOne) ClearEvidence() *APIKeyRiskEventUpdateOne {
	_u.mutation.ClearEvidence()
	return _u
}

// SetTimeBucket sets the "time_bucket" field.
func (_u *APIKeyRiskEventUpdateOne) SetTimeBucket(v time.Time) *APIKeyRiskEventUpdateOne {
	_u.mutation.SetTimeBucket(v)
	return _u
}

// SetNillableTimeBucket sets the "time_bucket" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdateOne) SetNillableTimeBucket(v *time.Time) *APIKeyRiskEventUpdateOne {
	if v != nil {
		_u.SetTimeBucket(*v)
	}
	return _u
}

// SetBlockedAt sets the "blocked_at" field.
func (_u *APIKeyRiskEventUpdateOne) SetBlockedAt(v time.Time) *APIKeyRiskEventUpdateOne {
	_u.mutation.SetBlockedAt(v)
	return _u
}

// SetNillableBlockedAt sets the "blocked_at" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdateOne) SetNillableBlockedAt(v *time.Time) *APIKeyRiskEventUpdateOne {
	if v != nil {
		_u.SetBlockedAt(*v)
	}
	return _u
}

// ClearBlockedAt clears the value of the "blocked_at" field.
func (_u *APIKeyRiskEventUpdateOne) ClearBlockedAt() *APIKeyRiskEventUpdateOne {
	_u.mutation.ClearBlockedAt()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *APIKeyRiskEventUpdateOne) SetResolvedAt(v time.Time) *APIKeyRiskEventUpdateOne {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdateOne) SetNillableResolvedAt(v *time.Time) *APIKeyRiskEventUpdateOne {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *APIKeyRiskEventUpdateOne) ClearResolvedAt() *APIKeyRiskEventUpdateOne {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetResolvedBy sets the "resolved_by" field.
func (_u *APIKeyRiskEventUpdateOne) SetResolvedBy(v int64) *APIKeyRiskEventUpdateOne {
	_u.mutation.ResetResolvedBy()
	_u.mutation.SetResolvedBy(v)
	return _u
}

// SetNillableResolvedBy sets the "resolved_by" field if the given value is not nil.
func (_u *APIKeyRiskEventUpdateOne) SetNillableResolvedBy(v *int64) *APIKeyRiskEventUpdateOne {
	if v != nil {
		_u.SetResolvedBy(*v)
	}
	return _u
}

// AddResolvedBy adds value to the "resolved_by" field.
func (_u *APIKeyRiskEventUpdateOne) AddResolvedBy(v int64) *APIKeyRiskEventUpdateOne {
	_u.mutation.AddResolvedBy(v)
	return _u
}

// ClearResolvedBy clears the value of the "resolved_by" field.
func (_u *APIKeyRiskEventUpdateOne) ClearResolvedBy() *APIKeyRiskEventUpdateOne {
	_u.mutation.ClearResolvedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyRiskEventUpdateOne) SetUpdatedAt(v time.Time) *APIKeyRiskEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *APIKeyRiskEventUpdateOne) SetUser(v *User) *APIKeyRiskEventUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *APIKeyRiskEventUpdateOne) SetAPIKey(v *APIKey) *APIKeyRiskEventUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the APIKeyRiskEventMutation object of the builder.
func (_u *APIKeyRiskEventUpdateOne) Mutation() *APIKeyRiskEventMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *APIKeyRiskEventUpdateOne) ClearUser() *APIKeyRiskEventUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *APIKeyRiskEventUpdateOne) ClearAPIKey() *APIKeyRiskEventUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// Where appends a list predicates to the APIKeyRiskEventUpdate builder.
func (_u *APIKeyRiskEventUpdateOne) Where(ps ...predicate.APIKeyRiskEvent) *APIKeyRiskEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeyRiskEventUpdateOne) Select(field string, fields ...string) *APIKeyRiskEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKeyRiskEvent entity.
func (_u *APIKeyRiskEventUpdateOne) Save(ctx context.Context) (*APIKeyRiskEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyRiskEventUpdateOne) SaveX(ctx context.Context) *APIKeyRiskEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeyRiskEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyRiskEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyRiskEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeyriskevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyRiskEventUpdateOne) check() error {
	if v, ok := _u.mutation.RuleCode(); ok {
		if err := apikeyriskevent.RuleCodeValidator(v); err != nil {
			return &ValidationError{Name: "rule_code", err: fmt.Errorf(`ent: validator failed for field "APIKeyRiskEvent.rule_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := apikeyriskevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "APIKeyRiskEvent.severity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := apikeyriskevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "APIKeyRiskEvent.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyRiskEvent.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyRiskEvent.api_key"`)
	}
	return nil
}

func (_u *APIKeyRiskEventUpdateOne) sqlSave(ctx context.Context) (_node *APIKeyRiskEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeyriskevent.Table, apikeyriskevent.Columns, sqlgraph.NewFieldSpec(apikeyriskevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKeyRiskEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikeyriskevent.FieldID)
		for _, f := range fields {
			if !apikeyriskevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikeyriskevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RuleCode(); ok {
		_spec.SetField(apikeyriskevent.FieldRuleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(apikeyriskevent.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(apikeyriskevent.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(apikeyriskevent.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(apikeyriskevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Evidence(); ok {
		_spec.SetField(apikeyriskevent.FieldEvidence, field.TypeJSON, value)
	}
	if _u.mutation.EvidenceCleared() {
		_spec.ClearField(apikeyriskevent.FieldEvidence, field.TypeJSON)
	}
	if value, ok := _u.mutation.TimeBucket(); ok {
		_spec.SetField(apikeyriskevent.FieldTimeBucket, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BlockedAt(); ok {
		_spec.SetField(apikeyriskevent.FieldBlockedAt, field.TypeTime, value)
	}
	if _u.mutation.BlockedAtCleared() {
		_spec.ClearField(apikeyriskevent.FieldBlockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(apikeyriskevent.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(apikeyriskevent.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResolvedBy(); ok {
		_spec.SetField(apikeyriskevent.FieldResolvedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResolvedBy(); ok {
		_spec.AddField(apikeyriskevent.FieldResolvedBy, field.TypeInt64, value)
	}
	if _u.mutation.ResolvedByCleared() {
		_spec.ClearField(apikeyriskevent.FieldResolvedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyriskevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyriskevent.UserTable,
			Columns: []string{apikeyriskevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyriskevent.UserTable,
			Columns: []string{apikeyriskevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyriskevent.APIKeyTable,
			Columns: []string{apikeyriskevent.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyriskevent.APIKeyTable,
			Columns: []string{apikeyriskevent.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &APIKeyRiskEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeyriskevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
