// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeyriskevent"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// APIKeyRiskEventCreate is the builder for creating a APIKeyRiskEvent entity.
type APIKeyRiskEventCreate struct {
	config
	mutation *APIKeyRiskEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *APIKeyRiskEventCreate) SetUserID(v int64) *APIKeyRiskEventCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *APIKeyRiskEventCreate) SetAPIKeyID(v int64) *APIKeyRiskEventCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetRuleCode sets the "rule_code" field.
func (_c *APIKeyRiskEventCreate) SetRuleCode(v string) *APIKeyRiskEventCreate {
	_c.mutation.SetRuleCode(v)
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *APIKeyRiskEventCreate) SetSeverity(v string) *APIKeyRiskEventCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetScore sets the "score" field.
func (_c *APIKeyRiskEventCreate) SetScore(v int) *APIKeyRiskEventCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_c *APIKeyRiskEventCreate) SetNillableScore(v *int) *APIKeyRiskEventCreate {
	if v != nil {
		_c.SetScore(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *APIKeyRiskEventCreate) SetStatus(v string) *APIKeyRiskEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *APIKeyRiskEventCreate) SetNillableStatus(v *string) *APIKeyRiskEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetEvidence sets the "evidence" field.
func (_c *APIKeyRiskEventCreate) SetEvidence(v map[string]interface{}) *APIKeyRiskEventCreate {
	_c.mutation.SetEvidence(v)
	return _c
}

// SetTimeBucket sets the "time_bucket" field.
func (_c *APIKeyRiskEventCreate) SetTimeBucket(v time.Time) *APIKeyRiskEventCreate {
	_c.mutation.SetTimeBucket(v)
	return _c
}

// SetBlockedAt sets the "blocked_at" field.
func (_c *APIKeyRiskEventCreate) SetBlockedAt(v time.Time) *APIKeyRiskEventCreate {
	_c.mutation.SetBlockedAt(v)
	return _c
}

// SetNillableBlockedAt sets the "blocked_at" field if the given value is not nil.
func (_c *APIKeyRiskEventCreate) SetNillableBlockedAt(v *time.Time) *APIKeyRiskEventCreate {
	if v != nil {
		_c.SetBlockedAt(*v)
	}
	return _c
}

// SetResolvedAt sets the "resolved_at" field.
func (_c *APIKeyRiskEventCreate) SetResolvedAt(v time.Time) *APIKeyRiskEventCreate {
	_c.mutation.SetResolvedAt(v)
	return _c
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_c *APIKeyRiskEventCreate) SetNillableResolvedAt(v *time.Time) *APIKeyRiskEventCreate {
	if v != nil {
		_c.SetResolvedAt(*v)
	}
	return _c
}

// SetResolvedBy sets the "resolved_by" field.
func (_c *APIKeyRiskEventCreate) SetResolvedBy(v int64) *APIKeyRiskEventCreate {
	_c.mutation.SetResolvedBy(v)
	return _c
}

// SetNillableResolvedBy sets the "resolved_by" field if the given value is not nil.
func (_c *APIKeyRiskEventCreate) SetNillableResolvedBy(v *int64) *APIKeyRiskEventCreate {
	if v != nil {
		_c.SetResolvedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *APIKeyRiskEventCreate) SetCreatedAt(v time.Time) *APIKeyRiskEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APIKeyRiskEventCreate) SetNillableCreatedAt(v *time.Time) *APIKeyRiskEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *APIKeyRiskEventCreate) SetUpdatedAt(v time.Time) *APIKeyRiskEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *APIKeyRiskEventCreate) SetNillableUpdatedAt(v *time.Time) *APIKeyRiskEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *APIKeyRiskEventCreate) SetUser(v *User) *APIKeyRiskEventCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *APIKeyRiskEventCreate) SetAPIKey(v *APIKey) *APIKeyRiskEventCreate {
	return _c.SetAPIKeyID(v.ID)
}

// Mutation returns the APIKeyRiskEventMutation object of the builder.
func (_c *APIKeyRiskEventCreate) Mutation() *APIKeyRiskEventMutation {
	return _c.mutation
}

// Save creates the APIKeyRiskEvent in the database.
func (_c *APIKeyRiskEventCreate) Save(ctx context.Context) (*APIKeyRiskEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIKeyRiskEventCreate) SaveX(ctx context.Context) *APIKeyRiskEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyRiskEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyRiskEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APIKeyRiskEventCreate) defaults() {
	if _, ok := _c.mutation.Score(); !ok {
		v := apikeyriskevent.DefaultScore
		_c.mutation.SetScore(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := apikeyriskevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apikeyriskevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apikeyriskevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIKeyRiskEventCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "APIKeyRiskEvent.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "APIKeyRiskEvent.api_key_id"`)}
	}
	if _, ok := _c.mutation.RuleCode(); !ok {
		return &ValidationError{Name: "rule_code", err: errors.New(`ent: missing required field "APIKeyRiskEvent.rule_code"`)}
	}
	if v, ok := _c.mutation.RuleCode(); ok {
		if err := apikeyriskevent.RuleCodeValidator(v); err != nil {
			return &ValidationError{Name: "rule_code", err: fmt.Errorf(`ent: validator failed for field "APIKeyRiskEvent.rule_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "APIKeyRiskEvent.severity"`)}
	}
	if v, ok := _c.mutation.Severity(); ok {
		if err := apikeyriskevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "APIKeyRiskEvent.severity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "APIKeyRiskEvent.score"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "APIKeyRiskEvent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := apikeyriskevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "APIKeyRiskEvent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TimeBucket(); !ok {
		return &ValidationError{Name: "time_bucket", err: errors.New(`ent: missing required field "APIKeyRiskEvent.time_bucket"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APIKeyRiskEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "APIKeyRiskEvent.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "APIKeyRiskEvent.user"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "APIKeyRiskEvent.api_key"`)}
	}
	return nil
}

func (_c *APIKeyRiskEventCreate) sqlSave(ctx context.Context) (*APIKeyRiskEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIKeyRiskEventCreate) createSpec() (*APIKeyRiskEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &APIKeyRiskEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikeyriskevent.Table, sqlgraph.NewFieldSpec(apikeyriskevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RuleCode(); ok {
		_spec.SetField(apikeyriskevent.FieldRuleCode, field.TypeString, value)
		_node.RuleCode = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(apikeyriskevent.FieldSeverity, field.TypeString, value)
		_node.Severity = value
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(apikeyriskevent.FieldScore, field.TypeInt, value)
		_node.Score = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(apikeyriskevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Evidence(); ok {
		_spec.SetField(apikeyriskevent.FieldEvidence, field.TypeJSON, value)
		_node.Evidence = value
	}
	if value, ok := _c.mutation.TimeBucket(); ok {
		_spec.SetField(apikeyriskevent.FieldTimeBucket, field.TypeTime, value)
		_node.TimeBucket = value
	}
	if value, ok := _c.mutation.BlockedAt(); ok {
		_spec.SetField(apikeyriskevent.FieldBlockedAt, field.TypeTime, value)
		_node.BlockedAt = &value
	}
	if value, ok := _c.mutation.ResolvedAt(); ok {
		_spec.SetField(apikeyriskevent.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	if value, ok := _c.mutation.ResolvedBy(); ok {
		_spec.SetField(apikeyriskevent.FieldResolvedBy, field.TypeInt64, value)
		_node.ResolvedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apikeyriskevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyriskevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyriskevent.UserTable,
			Columns: []string{apikeyriskevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyriskevent.APIKeyTable,
			Columns: []string{apikeyriskevent.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyRiskEvent.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyRiskEventUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyRiskEventCreate) OnConflict(opts ...sql.ConflictOption) *APIKeyRiskEventUpsertOne {
	_c.conflict = opts
	return &APIKeyRiskEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyRiskEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyRiskEventCreate) OnConflictColumns(columns ...string) *APIKeyRiskEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyRiskEventUpsertOne{
		create: _c,
	}
}

type (
	// APIKeyRiskEventUpsertOne is the builder for "upsert"-ing
	//  one APIKeyRiskEvent node.
	APIKeyRiskEventUpsertOne struct {
		create *APIKeyRiskEventCreate
	}

	// APIKeyRiskEventUpsert is the "OnConflict" setter.
	APIKeyRiskEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *APIKeyRiskEventUpsert) SetUserID(v int64) *APIKeyRiskEventUpsert {
	u.Set(apikeyriskevent.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsert) UpdateUserID() *APIKeyRiskEventUpsert {
	u.SetExcluded(apikeyriskevent.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyRiskEventUpsert) SetAPIKeyID(v int64) *APIKeyRiskEventUpsert {
	u.Set(apikeyriskevent.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsert) UpdateAPIKeyID() *APIKeyRiskEventUpsert {
	u.SetExcluded(apikeyriskevent.FieldAPIKeyID)
	return u
}

// SetRuleCode sets the "rule_code" field.
func (u *APIKeyRiskEventUpsert) SetRuleCode(v string) *APIKeyRiskEventUpsert {
	u.Set(apikeyriskevent.FieldRuleCode, v)
	return u
}

// UpdateRuleCode sets the "rule_code" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsert) UpdateRuleCode() *APIKeyRiskEventUpsert {
	u.SetExcluded(apikeyriskevent.FieldRuleCode)
	return u
}

// SetSeverity sets the "severity" field.
func (u *APIKeyRiskEventUpsert) SetSeverity(v string) *APIKeyRiskEventUpsert {
	u.Set(apikeyriskevent.FieldSeverity, v)
	return u
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsert) UpdateSeverity() *APIKeyRiskEventUpsert {
	u.SetExcluded(apikeyriskevent.FieldSeverity)
	return u
}

// SetScore sets the "score" field.
func (u *APIKeyRiskEventUpsert) SetScore(v int) *APIKeyRiskEventUpsert {
	u.Set(apikeyriskevent.FieldScore, v)
	return u
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsert) UpdateScore() *APIKeyRiskEventUpsert {
	u.SetExcluded(apikeyriskevent.FieldScore)
	return u
}

// AddScore adds v to the "score" field.
func (u *APIKeyRiskEventUpsert) AddScore(v int) *APIKeyRiskEventUpsert {
	u.Add(apikeyriskevent.FieldScore, v)
	return u
}

// SetStatus sets the "status" field.
func (u *APIKeyRiskEventUpsert) SetStatus(v string) *APIKeyRiskEventUpsert {
	u.Set(apikeyriskevent.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsert) UpdateStatus() *APIKeyRiskEventUpsert {
	u.SetExcluded(apikeyriskevent.FieldStatus)
	return u
}

// SetEvidence sets the "evidence" field.
func (u *APIKeyRiskEventUpsert) SetEvidence(v map[string]interface{}) *APIKeyRiskEventUpsert {
	u.Set(apikeyriskevent.FieldEvidence, v)
	return u
}

// UpdateEvidence sets the "evidence" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsert) UpdateEvidence() *APIKeyRiskEventUpsert {
	u.SetExcluded(apikeyriskevent.FieldEvidence)
	return u
}

// ClearEvidence clears the value of the "evidence" field.
func (u *APIKeyRiskEventUpsert) ClearEvidence() *APIKeyRiskEventUpsert {
	u.SetNull(apikeyriskevent.FieldEvidence)
	return u
}

// SetTimeBucket sets the "time_bucket" field.
func (u *APIKeyRiskEventUpsert) SetTimeBucket(v time.Time) *APIKeyRiskEventUpsert {
	u.Set(apikeyriskevent.FieldTimeBucket, v)
	return u
}

// UpdateTimeBucket sets the "time_bucket" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsert) UpdateTimeBucket() *APIKeyRiskEventUpsert {
	u.SetExcluded(apikeyriskevent.FieldTimeBucket)
	return u
}

// SetBlockedAt sets the "blocked_at" field.
func (u *APIKeyRiskEventUpsert) SetBlockedAt(v time.Time) *APIKeyRiskEventUpsert {
	u.Set(apikeyriskevent.FieldBlockedAt, v)
	return u
}

// UpdateBlockedAt sets the "blocked_at" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsert) UpdateBlockedAt() *APIKeyRiskEventUpsert {
	u.SetExcluded(apikeyriskevent.FieldBlockedAt)
	return u
}

// ClearBlockedAt clears the value of the "blocked_at" field.
func (u *APIKeyRiskEventUpsert) ClearBlockedAt() *APIKeyRiskEventUpsert {
	u.SetNull(apikeyriskevent.FieldBlockedAt)
	return u
}

// SetResolvedAt sets the "resolved_at" field.
func (u *APIKeyRiskEventUpsert) SetResolvedAt(v time.Time) *APIKeyRiskEventUpsert {
	u.Set(apikeyriskevent.FieldResolvedAt, v)
	return u
}

// UpdateResolvedAt sets the "resolved_at" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsert) UpdateResolvedAt() *APIKeyRiskEventUpsert {
	u.SetExcluded(apikeyriskevent.FieldResolvedAt)
	return u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (u *APIKeyRiskEventUpsert) ClearResolvedAt() *APIKeyRiskEventUpsert {
	u.SetNull(apikeyriskevent.FieldResolvedAt)
	return u
}

// SetResolvedBy sets the "resolved_by" field.
func (u *APIKeyRiskEventUpsert) SetResolvedBy(v int64) *APIKeyRiskEventUpsert {
	u.Set(apikeyriskevent.FieldResolvedBy, v)
	return u
}

// UpdateResolvedBy sets the "resolved_by" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsert) UpdateResolvedBy() *APIKeyRiskEventUpsert {
	u.SetExcluded(apikeyriskevent.FieldResolvedBy)
	return u
}

// AddResolvedBy adds v to the "resolved_by" field.
func (u *APIKeyRiskEventUpsert) AddResolvedBy(v int64) *APIKeyRiskEventUpsert {
	u.Add(apikeyriskevent.FieldResolvedBy, v)
	return u
}

// ClearResolvedBy clears the value of the "resolved_by" field.
func (u *APIKeyRiskEventUpsert) ClearResolvedBy() *APIKeyRiskEventUpsert {
	u.SetNull(apikeyriskevent.FieldResolvedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyRiskEventUpsert) SetUpdatedAt(v time.Time) *APIKeyRiskEventUpsert {
	u.Set(apikeyriskevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsert) UpdateUpdatedAt() *APIKeyRiskEventUpsert {
	u.SetExcluded(apikeyriskevent.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.APIKeyRiskEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyRiskEventUpsertOne) UpdateNewValues() *APIKeyRiskEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apikeyriskevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyRiskEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APIKeyRiskEventUpsertOne) Ignore() *APIKeyRiskEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyRiskEventUpsertOne) DoNothing() *APIKeyRiskEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyRiskEventCreate.OnConflict
// documentation for more info.
func (u *APIKeyRiskEventUpsertOne) Update(set func(*APIKeyRiskEventUpsert)) *APIKeyRiskEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyRiskEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *APIKeyRiskEventUpsertOne) SetUserID(v int64) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertOne) UpdateUserID() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyRiskEventUpsertOne) SetAPIKeyID(v int64) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertOne) UpdateAPIKeyID() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetRuleCode sets the "rule_code" field.
func (u *APIKeyRiskEventUpsertOne) SetRuleCode(v string) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetRuleCode(v)
	})
}

// UpdateRuleCode sets the "rule_code" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertOne) UpdateRuleCode() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateRuleCode()
	})
}

// SetSeverity sets the "severity" field.
func (u *APIKeyRiskEventUpsertOne) SetSeverity(v string) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertOne) UpdateSeverity() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateSeverity()
	})
}

// SetScore sets the "score" field.
func (u *APIKeyRiskEventUpsertOne) SetScore(v int) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *APIKeyRiskEventUpsertOne) AddScore(v int) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertOne) UpdateScore() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateScore()
	})
}

// SetStatus sets the "status" field.
func (u *APIKeyRiskEventUpsertOne) SetStatus(v string) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertOne) UpdateStatus() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateStatus()
	})
}

// SetEvidence sets the "evidence" field.
func (u *APIKeyRiskEventUpsertOne) SetEvidence(v map[string]interface{}) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetEvidence(v)
	})
}

// UpdateEvidence sets the "evidence" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertOne) UpdateEvidence() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateEvidence()
	})
}

// ClearEvidence clears the value of the "evidence" field.
func (u *APIKeyRiskEventUpsertOne) ClearEvidence() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.ClearEvidence()
	})
}

// SetTimeBucket sets the "time_bucket" field.
func (u *APIKeyRiskEventUpsertOne) SetTimeBucket(v time.Time) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetTimeBucket(v)
	})
}

// UpdateTimeBucket sets the "time_bucket" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertOne) UpdateTimeBucket() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateTimeBucket()
	})
}

// SetBlockedAt sets the "blocked_at" field.
func (u *APIKeyRiskEventUpsertOne) SetBlockedAt(v time.Time) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetBlockedAt(v)
	})
}

// UpdateBlockedAt sets the "blocked_at" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertOne) UpdateBlockedAt() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateBlockedAt()
	})
}

// ClearBlockedAt clears the value of the "blocked_at" field.
func (u *APIKeyRiskEventUpsertOne) ClearBlockedAt() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.ClearBlockedAt()
	})
}

// SetResolvedAt sets the "resolved_at" field.
func (u *APIKeyRiskEventUpsertOne) SetResolvedAt(v time.Time) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetResolvedAt(v)
	})
}

// UpdateResolvedAt sets the "resolved_at" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertOne) UpdateResolvedAt() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateResolvedAt()
	})
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (u *APIKeyRiskEventUpsertOne) ClearResolvedAt() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.ClearResolvedAt()
	})
}

// SetResolvedBy sets the "resolved_by" field.
func (u *APIKeyRiskEventUpsertOne) SetResolvedBy(v int64) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetResolvedBy(v)
	})
}

// AddResolvedBy adds v to the "resolved_by" field.
func (u *APIKeyRiskEventUpsertOne) AddResolvedBy(v int64) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.AddResolvedBy(v)
	})
}

// UpdateResolvedBy sets the "resolved_by" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertOne) UpdateResolvedBy() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateResolvedBy()
	})
}

// ClearResolvedBy clears the value of the "resolved_by" field.
func (u *APIKeyRiskEventUpsertOne) ClearResolvedBy() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.ClearResolvedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyRiskEventUpsertOne) SetUpdatedAt(v time.Time) *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertOne) UpdateUpdatedAt() *APIKeyRiskEventUpsertOne {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *APIKeyRiskEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyRiskEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyRiskEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APIKeyRiskEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APIKeyRiskEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APIKeyRiskEventCreateBulk is the builder for creating many APIKeyRiskEvent entities in bulk.
type APIKeyRiskEventCreateBulk struct {
	config
	err      error
	builders []*APIKeyRiskEventCreate
	conflict []sql.ConflictOption
}

// Save creates the APIKeyRiskEvent entities in the database.
func (_c *APIKeyRiskEventCreateBulk) Save(ctx context.Context) ([]*APIKeyRiskEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIKeyRiskEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIKeyRiskEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIKeyRiskEventCreateBulk) SaveX(ctx context.Context) []*APIKeyRiskEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyRiskEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyRiskEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyRiskEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyRiskEventUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyRiskEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *APIKeyRiskEventUpsertBulk {
	_c.conflict = opts
	return &APIKeyRiskEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyRiskEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyRiskEventCreateBulk) OnConflictColumns(columns ...string) *APIKeyRiskEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyRiskEventUpsertBulk{
		create: _c,
	}
}

// APIKeyRiskEventUpsertBulk is the builder for "upsert"-ing
// a bulk of APIKeyRiskEvent nodes.
type APIKeyRiskEventUpsertBulk struct {
	create *APIKeyRiskEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIKeyRiskEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyRiskEventUpsertBulk) UpdateNewValues() *APIKeyRiskEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apikeyriskevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyRiskEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APIKeyRiskEventUpsertBulk) Ignore() *APIKeyRiskEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyRiskEventUpsertBulk) DoNothing() *APIKeyRiskEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyRiskEventCreateBulk.OnConflict
// documentation for more info.
func (u *APIKeyRiskEventUpsertBulk) Update(set func(*APIKeyRiskEventUpsert)) *APIKeyRiskEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyRiskEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *APIKeyRiskEventUpsertBulk) SetUserID(v int64) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertBulk) UpdateUserID() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyRiskEventUpsertBulk) SetAPIKeyID(v int64) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertBulk) UpdateAPIKeyID() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetRuleCode sets the "rule_code" field.
func (u *APIKeyRiskEventUpsertBulk) SetRuleCode(v string) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetRuleCode(v)
	})
}

// UpdateRuleCode sets the "rule_code" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertBulk) UpdateRuleCode() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateRuleCode()
	})
}

// SetSeverity sets the "severity" field.
func (u *APIKeyRiskEventUpsertBulk) SetSeverity(v string) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertBulk) UpdateSeverity() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateSeverity()
	})
}

// SetScore sets the "score" field.
func (u *APIKeyRiskEventUpsertBulk) SetScore(v int) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *APIKeyRiskEventUpsertBulk) AddScore(v int) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertBulk) UpdateScore() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateScore()
	})
}

// SetStatus sets the "status" field.
func (u *APIKeyRiskEventUpsertBulk) SetStatus(v string) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertBulk) UpdateStatus() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateStatus()
	})
}

// SetEvidence sets the "evidence" field.
func (u *APIKeyRiskEventUpsertBulk) SetEvidence(v map[string]interface{}) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetEvidence(v)
	})
}

// UpdateEvidence sets the "evidence" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertBulk) UpdateEvidence() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateEvidence()
	})
}

// ClearEvidence clears the value of the "evidence" field.
func (u *APIKeyRiskEventUpsertBulk) ClearEvidence() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.ClearEvidence()
	})
}

// SetTimeBucket sets the "time_bucket" field.
func (u *APIKeyRiskEventUpsertBulk) SetTimeBucket(v time.Time) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetTimeBucket(v)
	})
}

// UpdateTimeBucket sets the "time_bucket" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertBulk) UpdateTimeBucket() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateTimeBucket()
	})
}

// SetBlockedAt sets the "blocked_at" field.
func (u *APIKeyRiskEventUpsertBulk) SetBlockedAt(v time.Time) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetBlockedAt(v)
	})
}

// UpdateBlockedAt sets the "blocked_at" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertBulk) UpdateBlockedAt() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateBlockedAt()
	})
}

// ClearBlockedAt clears the value of the "blocked_at" field.
func (u *APIKeyRiskEventUpsertBulk) ClearBlockedAt() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.ClearBlockedAt()
	})
}

// SetResolvedAt sets the "resolved_at" field.
func (u *APIKeyRiskEventUpsertBulk) SetResolvedAt(v time.Time) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetResolvedAt(v)
	})
}

// UpdateResolvedAt sets the "resolved_at" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertBulk) UpdateResolvedAt() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateResolvedAt()
	})
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (u *APIKeyRiskEventUpsertBulk) ClearResolvedAt() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.ClearResolvedAt()
	})
}

// SetResolvedBy sets the "resolved_by" field.
func (u *APIKeyRiskEventUpsertBulk) SetResolvedBy(v int64) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetResolvedBy(v)
	})
}

// AddResolvedBy adds v to the "resolved_by" field.
func (u *APIKeyRiskEventUpsertBulk) AddResolvedBy(v int64) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.AddResolvedBy(v)
	})
}

// UpdateResolvedBy sets the "resolved_by" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertBulk) UpdateResolvedBy() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateResolvedBy()
	})
}

// ClearResolvedBy clears the value of the "resolved_by" field.
func (u *APIKeyRiskEventUpsertBulk) ClearResolvedBy() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.ClearResolvedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyRiskEventUpsertBulk) SetUpdatedAt(v time.Time) *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyRiskEventUpsertBulk) UpdateUpdatedAt() *APIKeyRiskEventUpsertBulk {
	return u.Update(func(s *APIKeyRiskEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *APIKeyRiskEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the APIKeyRiskEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyRiskEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyRiskEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
