// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeyriskevent"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// APIKeyRiskEvent is the model entity for the APIKeyRiskEvent schema.
type APIKeyRiskEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// RuleCode holds the value of the "rule_code" field.
	RuleCode string `json:"rule_code,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity string `json:"severity,omitempty"`
	// Score holds the value of the "score" field.
	Score int `json:"score,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Evidence holds the value of the "evidence" field.
	Evidence map[string]interface{} `json:"evidence,omitempty"`
	// TimeBucket holds the value of the "time_bucket" field.
	TimeBucket time.Time `json:"time_bucket,omitempty"`
	// BlockedAt holds the value of the "blocked_at" field.
	BlockedAt *time.Time `json:"blocked_at,omitempty"`
	// ResolvedAt holds the value of the "resolved_at" field.
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// ResolvedBy holds the value of the "resolved_by" field.
	ResolvedBy *int64 `json:"resolved_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the APIKeyRiskEventQuery when eager-loading is set.
	Edges        APIKeyRiskEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// APIKeyRiskEventEdges holds the relations/edges for other nodes in the graph.
type APIKeyRiskEventEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIKeyRiskEventEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIKeyRiskEventEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*APIKeyRiskEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikeyriskevent.FieldEvidence:
			values[i] = new([]byte)
		case apikeyriskevent.FieldID, apikeyriskevent.FieldUserID, apikeyriskevent.FieldAPIKeyID, apikeyriskevent.FieldScore, apikeyriskevent.FieldResolvedBy:
			values[i] = new(sql.NullInt64)
		case apikeyriskevent.FieldRuleCode, apikeyriskevent.FieldSeverity, apikeyriskevent.FieldStatus:
			values[i] = new(sql.NullString)
		case apikeyriskevent.FieldTimeBucket, apikeyriskevent.FieldBlockedAt, apikeyriskevent.FieldResolvedAt, apikeyriskevent.FieldCreatedAt, apikeyriskevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the APIKeyRiskEvent fields.
func (_m *APIKeyRiskEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikeyriskevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case apikeyriskevent.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case apikeyriskevent.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case apikeyriskevent.FieldRuleCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_code", values[i])
			} else if value.Valid {
				_m.RuleCode = value.String
			}
		case apikeyriskevent.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = value.String
			}
		case apikeyriskevent.FieldScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = int(value.Int64)
			}
		case apikeyriskevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case apikeyriskevent.FieldEvidence:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field evidence", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Evidence); err != nil {
					return fmt.Errorf("unmarshal field evidence: %w", err)
				}
			}
		case apikeyriskevent.FieldTimeBucket:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field time_bucket", values[i])
			} else if value.Valid {
				_m.TimeBucket = value.Time
			}
		case apikeyriskevent.FieldBlockedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field blocked_at", values[i])
			} else if value.Valid {
				_m.BlockedAt = new(time.Time)
				*_m.BlockedAt = value.Time
			}
		case apikeyriskevent.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = new(time.Time)
				*_m.ResolvedAt = value.Time
			}
		case apikeyriskevent.FieldResolvedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_by", values[i])
			} else if value.Valid {
				_m.ResolvedBy = new(int64)
				*_m.ResolvedBy = value.Int64
			}
		case apikeyriskevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case apikeyriskevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the APIKeyRiskEvent.
// This includes values selected through modifiers, order, etc.
func (_m *APIKeyRiskEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the APIKeyRiskEvent entity.
func (_m *APIKeyRiskEvent) QueryUser() *UserQuery {
	return NewAPIKeyRiskEventClient(_m.config).QueryUser(_m)
}

// QueryAPIKey queries the "api_key" edge of the APIKeyRiskEvent entity.
func (_m *APIKeyRiskEvent) QueryAPIKey() *APIKeyQuery {
	return NewAPIKeyRiskEventClient(_m.config).QueryAPIKey(_m)
}

// Update returns a builder for updating this APIKeyRiskEvent.
// Note that you need to call APIKeyRiskEvent.Unwrap() before calling this method if this APIKeyRiskEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *APIKeyRiskEvent) Update() *APIKeyRiskEventUpdateOne {
	return NewAPIKeyRiskEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the APIKeyRiskEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *APIKeyRiskEvent) Unwrap() *APIKeyRiskEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: APIKeyRiskEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *APIKeyRiskEvent) String() string {
	var builder strings.Builder
	builder.WriteString("APIKeyRiskEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("rule_code=")
	builder.WriteString(_m.RuleCode)
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(_m.Severity)
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("evidence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Evidence))
	builder.WriteString(", ")
	builder.WriteString("time_bucket=")
	builder.WriteString(_m.TimeBucket.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.BlockedAt; v != nil {
		builder.WriteString("blocked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ResolvedBy; v != nil {
		builder.WriteString("resolved_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// APIKeyRiskEvents is a parsable slice of APIKeyRiskEvent.
type APIKeyRiskEvents []*APIKeyRiskEvent
