// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usermessage"
)

// UserMessageUpdate is the builder for updating UserMessage entities.
type UserMessageUpdate struct {
	config
	hooks    []Hook
	mutation *UserMessageMutation
}

// Where appends a list predicates to the UserMessageUpdate builder.
func (_u *UserMessageUpdate) Where(ps ...predicate.UserMessage) *UserMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserMessageUpdate) SetUserID(v int64) *UserMessageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserMessageUpdate) SetNillableUserID(v *int64) *UserMessageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *UserMessageUpdate) SetType(v string) *UserMessageUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *UserMessageUpdate) SetNillableType(v *string) *UserMessageUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *UserMessageUpdate) SetTitle(v string) *UserMessageUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *UserMessageUpdate) SetNillableTitle(v *string) *UserMessageUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *UserMessageUpdate) SetContent(v string) *UserMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *UserMessageUpdate) SetNillableContent(v *string) *UserMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserMessageUpdate) SetStatus(v string) *UserMessageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserMessageUpdate) SetNillableStatus(v *string) *UserMessageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *UserMessageUpdate) SetMetadata(v map[string]interface{}) *UserMessageUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *UserMessageUpdate) ClearMetadata() *UserMessageUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *UserMessageUpdate) SetReadAt(v time.Time) *UserMessageUpdate {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *UserMessageUpdate) SetNillableReadAt(v *time.Time) *UserMessageUpdate {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *UserMessageUpdate) ClearReadAt() *UserMessageUpdate {
	_u.mutation.ClearReadAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserMessageUpdate) SetUpdatedAt(v time.Time) *UserMessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserMessageUpdate) SetUser(v *User) *UserMessageUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserMessageMutation object of the builder.
func (_u *UserMessageUpdate) Mutation() *UserMessageMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserMessageUpdate) ClearUser() *UserMessageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserMessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserMessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usermessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserMessageUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := usermessage.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UserMessage.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := usermessage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "UserMessage.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := usermessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "UserMessage.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := usermessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserMessage.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserMessage.user"`)
	}
	return nil
}

func (_u *UserMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usermessage.Table, usermessage.Columns, sqlgraph.NewFieldSpec(usermessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(usermessage.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(usermessage.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(usermessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usermessage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(usermessage.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(usermessage.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(usermessage.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(usermessage.FieldReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usermessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usermessage.UserTable,
			Columns: []string{usermessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usermessage.UserTable,
			Columns: []string{usermessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usermessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserMessageUpdateOne is the builder for updating a single UserMessage entity.
type UserMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMessageMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserMessageUpdateOne) SetUserID(v int64) *UserMessageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserMessageUpdateOne) SetNillableUserID(v *int64) *UserMessageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *UserMessageUpdateOne) SetType(v string) *UserMessageUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *UserMessageUpdateOne) SetNillableType(v *string) *UserMessageUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *UserMessageUpdateOne) SetTitle(v string) *UserMessageUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *UserMessageUpdateOne) SetNillableTitle(v *string) *UserMessageUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *UserMessageUpdateOne) SetContent(v string) *UserMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *UserMessageUpdateOne) SetNillableContent(v *string) *UserMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserMessageUpdateOne) SetStatus(v string) *UserMessageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserMessageUpdateOne) SetNillableStatus(v *string) *UserMessageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *UserMessageUpdateOne) SetMetadata(v map[string]interface{}) *UserMessageUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *UserMessageUpdateOne) ClearMetadata() *UserMessageUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *UserMessageUpdateOne) SetReadAt(v time.Time) *UserMessageUpdateOne {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *UserMessageUpdateOne) SetNillableReadAt(v *time.Time) *UserMessageUpdateOne {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *UserMessageUpdateOne) ClearReadAt() *UserMessageUpdateOne {
	_u.mutation.ClearReadAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserMessageUpdateOne) SetUpdatedAt(v time.Time) *UserMessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserMessageUpdateOne) SetUser(v *User) *UserMessageUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserMessageMutation object of the builder.
func (_u *UserMessageUpdateOne) Mutation() *UserMessageMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserMessageUpdateOne) ClearUser() *UserMessageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserMessageUpdate builder.
func (_u *UserMessageUpdateOne) Where(ps ...predicate.UserMessage) *UserMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserMessageUpdateOne) Select(field string, fields ...string) *UserMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserMessage entity.
func (_u *UserMessageUpdateOne) Save(ctx context.Context) (*UserMessage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserMessageUpdateOne) SaveX(ctx context.Context) *UserMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserMessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usermessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserMessageUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := usermessage.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UserMessage.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := usermessage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "UserMessage.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := usermessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "UserMessage.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := usermessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserMessage.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserMessage.user"`)
	}
	return nil
}

func (_u *UserMessageUpdateOne) sqlSave(ctx context.Context) (_node *UserMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usermessage.Table, usermessage.Columns, sqlgraph.NewFieldSpec(usermessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usermessage.FieldID)
		for _, f := range fields {
			if !usermessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usermessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(usermessage.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(usermessage.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(usermessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usermessage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(usermessage.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(usermessage.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(usermessage.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(usermessage.FieldReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usermessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usermessage.UserTable,
			Columns: []string{usermessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usermessage.UserTable,
			Columns: []string{usermessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usermessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
