// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usermessage"
)

// UserMessageCreate is the builder for creating a UserMessage entity.
type UserMessageCreate struct {
	config
	mutation *UserMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserMessageCreate) SetUserID(v int64) *UserMessageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *UserMessageCreate) SetType(v string) *UserMessageCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *UserMessageCreate) SetTitle(v string) *UserMessageCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *UserMessageCreate) SetContent(v string) *UserMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserMessageCreate) SetStatus(v string) *UserMessageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserMessageCreate) SetNillableStatus(v *string) *UserMessageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *UserMessageCreate) SetMetadata(v map[string]interface{}) *UserMessageCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetReadAt sets the "read_at" field.
func (_c *UserMessageCreate) SetReadAt(v time.Time) *UserMessageCreate {
	_c.mutation.SetReadAt(v)
	return _c
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_c *UserMessageCreate) SetNillableReadAt(v *time.Time) *UserMessageCreate {
	if v != nil {
		_c.SetReadAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserMessageCreate) SetCreatedAt(v time.Time) *UserMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserMessageCreate) SetNillableCreatedAt(v *time.Time) *UserMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserMessageCreate) SetUpdatedAt(v time.Time) *UserMessageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserMessageCreate) SetNillableUpdatedAt(v *time.Time) *UserMessageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserMessageCreate) SetUser(v *User) *UserMessageCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserMessageMutation object of the builder.
func (_c *UserMessageCreate) Mutation() *UserMessageMutation {
	return _c.mutation
}

// Save creates the UserMessage in the database.
func (_c *UserMessageCreate) Save(ctx context.Context) (*UserMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserMessageCreate) SaveX(ctx context.Context) *UserMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserMessageCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := usermessage.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usermessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usermessage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserMessageCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserMessage.user_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "UserMessage.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := usermessage.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UserMessage.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "UserMessage.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := usermessage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "UserMessage.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "UserMessage.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := usermessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "UserMessage.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserMessage.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := usermessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserMessage.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserMessage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserMessage.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserMessage.user"`)}
	}
	return nil
}

func (_c *UserMessageCreate) sqlSave(ctx context.Context) (*UserMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserMessageCreate) createSpec() (*UserMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &UserMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usermessage.Table, sqlgraph.NewFieldSpec(usermessage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(usermessage.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(usermessage.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(usermessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(usermessage.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(usermessage.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.ReadAt(); ok {
		_spec.SetField(usermessage.FieldReadAt, field.TypeTime, value)
		_node.ReadAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usermessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usermessage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usermessage.UserTable,
			Columns: []string{usermessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserMessage.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserMessageUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserMessageCreate) OnConflict(opts ...sql.ConflictOption) *UserMessageUpsertOne {
	_c.conflict = opts
	return &UserMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserMessageCreate) OnConflictColumns(columns ...string) *UserMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserMessageUpsertOne{
		create: _c,
	}
}

type (
	// UserMessageUpsertOne is the builder for "upsert"-ing
	//  one UserMessage node.
	UserMessageUpsertOne struct {
		create *UserMessageCreate
	}

	// UserMessageUpsert is the "OnConflict" setter.
	UserMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserMessageUpsert) SetUserID(v int64) *UserMessageUpsert {
	u.Set(usermessage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserMessageUpsert) UpdateUserID() *UserMessageUpsert {
	u.SetExcluded(usermessage.FieldUserID)
	return u
}

// SetType sets the "type" field.
func (u *UserMessageUpsert) SetType(v string) *UserMessageUpsert {
	u.Set(usermessage.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *UserMessageUpsert) UpdateType() *UserMessageUpsert {
	u.SetExcluded(usermessage.FieldType)
	return u
}

// SetTitle sets the "title" field.
func (u *UserMessageUpsert) SetTitle(v string) *UserMessageUpsert {
	u.Set(usermessage.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *UserMessageUpsert) UpdateTitle() *UserMessageUpsert {
	u.SetExcluded(usermessage.FieldTitle)
	return u
}

// SetContent sets the "content" field.
func (u *UserMessageUpsert) SetContent(v string) *UserMessageUpsert {
	u.Set(usermessage.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *UserMessageUpsert) UpdateContent() *UserMessageUpsert {
	u.SetExcluded(usermessage.FieldContent)
	return u
}

// SetStatus sets the "status" field.
func (u *UserMessageUpsert) SetStatus(v string) *UserMessageUpsert {
	u.Set(usermessage.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserMessageUpsert) UpdateStatus() *UserMessageUpsert {
	u.SetExcluded(usermessage.FieldStatus)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *UserMessageUpsert) SetMetadata(v map[string]interface{}) *UserMessageUpsert {
	u.Set(usermessage.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *UserMessageUpsert) UpdateMetadata() *UserMessageUpsert {
	u.SetExcluded(usermessage.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *UserMessageUpsert) ClearMetadata() *UserMessageUpsert {
	u.SetNull(usermessage.FieldMetadata)
	return u
}

// SetReadAt sets the "read_at" field.
func (u *UserMessageUpsert) SetReadAt(v time.Time) *UserMessageUpsert {
	u.Set(usermessage.FieldReadAt, v)
	return u
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *UserMessageUpsert) UpdateReadAt() *UserMessageUpsert {
	u.SetExcluded(usermessage.FieldReadAt)
	return u
}

// ClearReadAt clears the value of the "read_at" field.
func (u *UserMessageUpsert) ClearReadAt() *UserMessageUpsert {
	u.SetNull(usermessage.FieldReadAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserMessageUpsert) SetUpdatedAt(v time.Time) *UserMessageUpsert {
	u.Set(usermessage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserMessageUpsert) UpdateUpdatedAt() *UserMessageUpsert {
	u.SetExcluded(usermessage.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserMessageUpsertOne) UpdateNewValues() *UserMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usermessage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserMessageUpsertOne) Ignore() *UserMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserMessageUpsertOne) DoNothing() *UserMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserMessageCreate.OnConflict
// documentation for more info.
func (u *UserMessageUpsertOne) Update(set func(*UserMessageUpsert)) *UserMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserMessageUpsertOne) SetUserID(v int64) *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserMessageUpsertOne) UpdateUserID() *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateUserID()
	})
}

// SetType sets the "type" field.
func (u *UserMessageUpsertOne) SetType(v string) *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *UserMessageUpsertOne) UpdateType() *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateType()
	})
}

// SetTitle sets the "title" field.
func (u *UserMessageUpsertOne) SetTitle(v string) *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *UserMessageUpsertOne) UpdateTitle() *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *UserMessageUpsertOne) SetContent(v string) *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *UserMessageUpsertOne) UpdateContent() *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateContent()
	})
}

// SetStatus sets the "status" field.
func (u *UserMessageUpsertOne) SetStatus(v string) *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserMessageUpsertOne) UpdateStatus() *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateStatus()
	})
}

// SetMetadata sets the "metadata" field.
func (u *UserMessageUpsertOne) SetMetadata(v map[string]interface{}) *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *UserMessageUpsertOne) UpdateMetadata() *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *UserMessageUpsertOne) ClearMetadata() *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.ClearMetadata()
	})
}

// SetReadAt sets the "read_at" field.
func (u *UserMessageUpsertOne) SetReadAt(v time.Time) *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetReadAt(v)
	})
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *UserMessageUpsertOne) UpdateReadAt() *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateReadAt()
	})
}

// ClearReadAt clears the value of the "read_at" field.
func (u *UserMessageUpsertOne) ClearReadAt() *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.ClearReadAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserMessageUpsertOne) SetUpdatedAt(v time.Time) *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserMessageUpsertOne) UpdateUpdatedAt() *UserMessageUpsertOne {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserMessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserMessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserMessageCreateBulk is the builder for creating many UserMessage entities in bulk.
type UserMessageCreateBulk struct {
	config
	err      error
	builders []*UserMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the UserMessage entities in the database.
func (_c *UserMessageCreateBulk) Save(ctx context.Context) ([]*UserMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserMessageCreateBulk) SaveX(ctx context.Context) []*UserMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserMessageUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserMessageUpsertBulk {
	_c.conflict = opts
	return &UserMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserMessageCreateBulk) OnConflictColumns(columns ...string) *UserMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserMessageUpsertBulk{
		create: _c,
	}
}

// UserMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of UserMessage nodes.
type UserMessageUpsertBulk struct {
	create *UserMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserMessageUpsertBulk) UpdateNewValues() *UserMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usermessage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserMessageUpsertBulk) Ignore() *UserMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserMessageUpsertBulk) DoNothing() *UserMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserMessageCreateBulk.OnConflict
// documentation for more info.
func (u *UserMessageUpsertBulk) Update(set func(*UserMessageUpsert)) *UserMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserMessageUpsertBulk) SetUserID(v int64) *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserMessageUpsertBulk) UpdateUserID() *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateUserID()
	})
}

// SetType sets the "type" field.
func (u *UserMessageUpsertBulk) SetType(v string) *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *UserMessageUpsertBulk) UpdateType() *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateType()
	})
}

// SetTitle sets the "title" field.
func (u *UserMessageUpsertBulk) SetTitle(v string) *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *UserMessageUpsertBulk) UpdateTitle() *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *UserMessageUpsertBulk) SetContent(v string) *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *UserMessageUpsertBulk) UpdateContent() *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateContent()
	})
}

// SetStatus sets the "status" field.
func (u *UserMessageUpsertBulk) SetStatus(v string) *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserMessageUpsertBulk) UpdateStatus() *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateStatus()
	})
}

// SetMetadata sets the "metadata" field.
func (u *UserMessageUpsertBulk) SetMetadata(v map[string]interface{}) *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *UserMessageUpsertBulk) UpdateMetadata() *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *UserMessageUpsertBulk) ClearMetadata() *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.ClearMetadata()
	})
}

// SetReadAt sets the "read_at" field.
func (u *UserMessageUpsertBulk) SetReadAt(v time.Time) *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetReadAt(v)
	})
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *UserMessageUpsertBulk) UpdateReadAt() *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateReadAt()
	})
}

// ClearReadAt clears the value of the "read_at" field.
func (u *UserMessageUpsertBulk) ClearReadAt() *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.ClearReadAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserMessageUpsertBulk) SetUpdatedAt(v time.Time) *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserMessageUpsertBulk) UpdateUpdatedAt() *UserMessageUpsertBulk {
	return u.Update(func(s *UserMessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
